In [1]:
import numpy as np

In [16]:
#Vector
v = [1,2]

#Matrix
m = [[1,2,3],
     [2,4,6]]

In [29]:
#Print a matrix which is 2 X 3
print(np.array(m))

[[1 2 3]
 [2 4 6]]


In [8]:
#Matric addition
m1 = [[1,2],[3,4]]
m2 = [[2,4],[4,5]]

matrix_add = []

for i in range(len(m1)):
    row = []                     # Create a new row
    for j in range(len(m1[0])):
        row.append(m1[i][j] + m2[i][j])   # Fill the row
    matrix_add.append(row)       # Add completed row to matrix
print(f"Matrix m1 + m2 = {matrix_add}")

Matrix m1 + m2 = [[3, 6], [7, 9]]


In [6]:
#Matrix addition using Numpy
np.add(m1,m2)

array([[3, 6],
       [7, 9]])

In [9]:
#Matrix subtraction
matrix_subtract = []

for i in range(len(m1)):
    row = []                     # Create a new row
    for j in range(len(m1[0])):
        row.append(m1[i][j] - m2[i][j])   # Fill the row
    matrix_subtract.append(row)       # Add completed row to matrix

print(f"Matrix m1 - m2 = {matrix_subtract}")

Matrix m1 - m2 = [[-1, -2], [-1, -1]]


In [10]:
#Matrix subtraction using numpy
np.subtract(m1,m2)

array([[-1, -2],
       [-1, -1]])

In [11]:
#Scalar and matrix multiplication
s = 3

scalar_matrix = []
for i in range(len(m1)):
    row= []
    for j in range(len(m1[0])):
        row.append(s* m1[i][j])
    scalar_matrix.append(row)
print(scalar_matrix)

[[3, 6], [9, 12]]


In [12]:
#Scalar and matrix multiplication using numpy
np.multiply(s,m1)

array([[ 3,  6],
       [ 9, 12]])

In [26]:
#Matric and vector multiplication
v = [1,2]

vector_matrix = []
for i in range(len(m1)):
    row = []
    for j in range(len(v)):
        row.append(m1[i][j]*v[j])
    vector_matrix.append(row)

print(vector_matrix)

[[1, 4], [3, 8]]


In [20]:
#Matric and vector multiplication using numpy 
np.multiply(m1,v)

array([[1, 4],
       [3, 8]])

In [28]:
#Matric shape function
def matrix_shape(a):
    return np.shape(a)

print(matrix_shape(m))

(2, 3)
