In [1]:
import numpy as np

In [72]:
#Matrix multiplication
m1 = [[1,2],
      [2,4]]
m2 = [[1,3],
      [2,6]]

def multiply(a,b):
    matrix_mul = []
    for i in range(len(a)):
        row = []
        for j in range(len(b[0])):
            total = 0
            for k in range(len(a[0])):
                total += a[i][k] * b[k][j]
            row.append(total)
        matrix_mul.append(row)
    return matrix_mul

print(multiply(m1,m2))

[[5, 15], [10, 30]]


In [75]:
#Matrix multiplicationo using numpy
np.matmul(m1,m2)

array([[ 5, 15],
       [10, 30]])

In [88]:
#Identity matrix
def identity(n):
    matrix = []
    for i in range(n):
        row = []
        for j in range(n):
            if i == j:
                row.append(1) 
            else:
                row.append(0)
        matrix.append(row)
    return np.array(matrix)

print(identity(4))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [89]:
#Identity matrix using numpy
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
#Check if multiplication works
def can_multiply(a,b):
    a = np.array(a)
    b = np.array(b)
    if a.shape[1] == b.shape[0]:
        return True
    else:
        return False

mat1 = [[1,2,3],[2,3,4]]
mat2 = [[1,2],[1,2]]
print(can_multiply(mat1,mat2))

dim1 = [[1,2],[2,3]]
dim2 = [[2,3],[2,3]]
print(can_multiply(dim1,dim2))

False
True
