In [9]:
import numpy as np

## Vectors

In [16]:
#add_vectors()
def add_vectors(v1,v2):
    sum_vector = []
    if len(v1) == len(v2):
        for i in range(len(v1)):
            sum_vector.append(v1[i]+v2[i])
        return sum_vector
    else: 
        return "Addition not possible"

In [17]:
a = [1,2,3,4,5]
b = [9,8,7,6,5]

print(add_vectors(a,b))

[10, 10, 10, 10, 10]


In [22]:
#vector addition using the numpy
np.add(a,b)

array([10, 10, 10, 10, 10])

In [18]:
#dot_product()

In [23]:
def dot_product(v1,v2):
    vector_dot_prod = 0
    if len(v1) == len(v2):
        for i in range(len(v1)):
            vector_dot_prod += (v1[i]*v2[i])
        return vector_dot_prod
    else:
        return "Dot product is not possible"

In [25]:
print(dot_product(a,b))

95


In [26]:
#Dot product using numpy
np.dot(a,b)

np.int64(95)

In [42]:
#norm()
def norm(v1):
    norm_of_vector = 0
    for i in v1:
        total = 0
        for j in range(len(v1)):
            total += (v1[j]**2)
    norm_of_vector += total**(1/2)
    return norm_of_vector

In [43]:
print(norm(a))

7.416198487095663


In [39]:
#norm using numpy
np.linalg.norm(a)

np.float64(7.416198487095663)

## Matrices

In [16]:
#Add matrix
a = [[1,2],[3,4]]
b = [[1,3],[2,4]]

n = [[1,2,3],[2,3,4]]

def add_matrices(m1,m2):
    if len(m1) == len(m2) & len(m1[0]) == len(m2[0]):
        matrix_sum = []
        for i in range(len(m1)):
            row = []
            for j in range(len(m1[0])):
                row.append(m1[i][j]+m2[i][j])
            matrix_sum.append(row)
        return matrix_sum
    
    else:
        return "Matrix addition is not possible"          

print(add_matrices(a,b))
print(add_matrices(a,n))

[[2, 5], [5, 8]]
Matrix addition is not possible


In [36]:
#Matrix addition using numpy
np.add(a,b)

array([[2, 5],
       [5, 8]])

In [19]:
#Multiply matrix
m = [[1,2,3],[4,5,6],[7,8,9]]

def matrix_mul(m1,m2):
    if len(m1[0]) == len(m2):
        matrix_product = []
        for i in range(len(m1)):
            row = []
            for j in range(len(m2[0])):
                total = 0
                for k in range(len(m1[0])):
                    total += m1[i][k] * m2[k][j]
                row.append(total)
            matrix_product.append(row)
        return matrix_product
    else:
        return "Matrix multiplication is not possible"

print(matrix_mul(a,b))
print(matrix_mul(a,n))
print(matrix_mul(a,m))

[[5, 11], [11, 25]]
[[5, 8, 11], [11, 18, 25]]
Matrix multiplication is not possible


In [35]:
#Matrix multiplication using numpy
np.matmul(a,b)

array([[ 5, 11],
       [11, 25]])

In [31]:
#Identity matrix
def identity(n):
    identity_matrix = []
    for i in range(n):
        row = []
        for j in range(n):
            if i == j:
                row.append(1)
            else:
                row.append(0)
        identity_matrix.append(row)
    return np.array(identity_matrix)

print(identity(3))
print(identity(5))

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [34]:
#Identity matrix using numpy
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
#Shape of a matrix
def shape_of_matrix(matrix):
    row = len(matrix)
    column = len(matrix[0])
    return f"Shape of matrix is {row}x{column}"

print(shape_of_matrix(a))
print(shape_of_matrix(n))
print(shape_of_matrix(m))

Shape of matrix is 2x2
Shape of matrix is 2x3
Shape of matrix is 3x3


In [38]:
#Shape of a matrix using numpy
print(np.shape(a))
print(np.shape(n))
print(np.shape(m))

(2, 2)
(2, 3)
(3, 3)
